export const categoria = ["about", "contact", "budin", "pastafrolas"];

export const itemss = [
  {
    categoria: "budin",
    producto: "vainilla",
    tamaño: "chico",
    precio: "3,000",
    image: "/src/assets/budin.jpg",
  },
  {
    categoria: "budin ",
    producto: "vainilla",
    tamaño: "grande",
    precio: 6.8,
    image: "/src/assets/budin.jpg",
  },
  {
    categoria: "budin",
    producto: "naranja",
    tamaño: "chico",
    precio: 3.8,
    image: "/src/assets/budin.jpg",
  },
  {
    categoria: "budin",
    producto: "naranja",
    tamaño: "grande",
    precio: 7.0,
    image: "/src/assets/budin.jpg",
  },
  {
    categoria: "budin",
    producto: "limon",
    tamaño: "chicos",
    precio: 3.8,
    image: "/src/assets/budin.jpg",
  },
  {
    categoria: "budin",
    producto: "limon",
    tamaño: "grande",
    precio: 7.0,
    image: "/src/assets/budin.jpg",
  },
  {
    categoria: "budin",
    producto: "banana",
    tamaño: "chico",
    precio: 3.9,
    image: "/src/assets/budin.jpg",
  },
  {
    categoria: "budin",
    producto: "banana",
    tamaño: "grande",
    precio: 8.0,
    image: "/src/assets/budin.jpg",
  },
  {
    categoria: "budin",
    producto: "zanahoria",
    tamaño: "chico",
    precio: 3.9,
    image: "/src/assets/budin.jpg",
  },
  {
    categoria: "budin",
    producto: "zanahoria",
    tamaño: "grande",
    precio: 8.0,
    image: "/src/assets/budin.jpg",
  },
  {
    categoria: "budin",
    producto: "chocobrownie",
    tamaño: "chico",
    precio: 3.9,
    image: "/src/assets/budin.jpg",
  },
  {
    categoria: "budin",
    producto: "chocobrownie",
    tamaño: "grande",
    precio: 8.0,
    image: "/src/assets/budin.jpg",
  },
  {
    categoria: "pastafrolas",
    producto: "membrillo",
    tamaño: "chico",
    precio: 4.0,
    image: "/src/assets/pastafrola.jpg",
  },
  {
    categoria: "pastafrolas",
    producto: "membrilla",
    tamaño: "grande",
    precio: 8.0,
    image: "/src/assets/pastafrola.jpg",
  },
  {
    categoria: "pastafrolas",
    producto: "batata",
    tamaño: "chico",
    precio: 4.0,
    image: "/src/assets/pastafrola.jpg",
  },
  {
    categoria: "pastafrolas",
    producto: "batata",
    tamaño: "grande",
    precio: 8.0,
    image: "/src/assets/pastafrola.jpg",
  },
  {
    categoria: "pastafrolas",
    producto: "mixta",
    tamaño: "chico",
    precio: 4.3,
    image: "/src/assets/pastafrola.jpg",
  },
  {
    categoria: "pastafrolas",
    producto: "mixta",
    tamaño: "grande",
    precio: 8.3,
    image: "/src/assets/pastafrola.jpg",
  },
  {
    categoria: "pastafrolas",
    producto: "ricota",
    tamaño: "chico",
    precio: 4.5,
    image: "/src/assets/pastafrola.jpg",
  },
  {
    categoria: "pastafrolas",
    producto: "ricota",
    tamaño: "grande",
    precio: 9.0,
    image: "/src/assets/pastafrola.jpg",
  },
  {
    categoria: "pastafrolas",
    producto: "ricota dulce de leche",
    tamaño: "chico",
    precio: 4.8,
    image: "/src/assets/pastafrola.jpg",
  },
  {
    categoria: "pastafrolas",
    producto: "ricota dulce de leche",
    tamaño: "grande",
    precio: 9.5,
    image: "/src/assets/pastafrola.jpg",
  },
];
