export const product = [ {
    id:1 ,
    categoria:"budines" ,
    producto: "vainilla",
    tamaño: "chico",
    precio: 3.600,
  },
  {
      id:2 ,
      categoria:"budines" ,
      producto: "vainilla",
      tamaño: "grande",
      precio: 6.800,
    },
    {
      id:3 ,
      categoria:"budines" ,
      producto:"naranja" ,
      tamaño: "chico",
      precio: 3.800,
    },
    {
      id: 4,
      categoria:"budines" ,
      producto: "naranja",
      tamaño: "grande",
      precio: 7.000,
    },
    {
      id: 5,
      categoria:"budines" ,
      producto: "limon",
      tamaño: "chicos",
      precio: 3.800,
    },
    {
      id: 6,
      categoria:"budines" ,
      producto: "limon",
      tamaño: "grande",
      precio: 7.000,
    },
    {
      id: 7,
      categoria:"budines" ,
      producto: "banana",
      tamaño: "chico",
      precio: 3.900,
    },
    {
      id: 8,
      categoria:"budines" ,
      producto: "banana",
      tamaño: "grande",
      precio: 8.000,
    },
    {
      id: 9,
      categoria:"budines" ,
      producto: "zanahoria",
      tamaño:"chico" ,
      precio: 3.900,
    },
    {
      id: 10,
      categoria:"budines" ,
      producto: "zanahoria",
      tamaño: "grande",
      precio: 8.000,
    },
    {
      id: 11,
      categoria:"budines" ,
      producto: "chocobrownie",
      tamaño: "chico",
      precio: 3.900,
    },
    {
      id:12 ,
      categoria:"budines" ,
      producto: "chocobrownie",
      tamaño: "grande",
      precio: 8.000,
    },
    {
      id:13 ,
      categoria:"pastafrolas" ,
      producto:"membrillo" ,
      tamaño: "chico",
      precio: 4.000,
    },
    {
      id: 14,
      categoria:"pastafrolas" ,
      producto: "membrilla",
      tamaño: "grande",
      precio: 8.000,
    },
    {
      id: 15,
      categoria:"pastafrolas" ,
      producto: "batata",
      tamaño: "chico",
      precio: 4.000,
    },
    {
      id: 16,
      categoria:"pastafrolas" ,
      producto: "batata",
      tamaño: "grande",
      precio: 8.000,
    },
    {
      id: 17,
      categoria:"pastafrolas" ,
      producto: "mixta",
      tamaño: "chico",
      precio: 4.300,
    },
    {
      id: 18,
      categoria:"pastafrolas" ,
      producto: "mixta",
      tamaño: "grande",
      precio: 8.300,
    },
    {
      id: 19,
      categoria:"pastafrolas" ,
      producto: "ricota",
      tamaño: "chico",
      precio: 4.500,
    },
    {
      id: 20,
      categoria:"pastafrolas" ,
      producto: "ricota",
      tamaño: "grande",
      precio: 9.000,
    },
    {
      id: 21,
      categoria:"pastafrolas" ,
      producto:"ricota dulce de leche" ,
      tamaño: "chico",
      precio: 4.800,
    },
    {
      id: 22,
      categoria:"pastafrolas" ,
      producto:"ricota dulce de leche" ,
      tamaño: "grande",
      precio: 9.500,
    }]